### ISSUE TITLE
Support for multiple snippets of code in a page

### ISSUE THREAD

**Issue by gabrielgodoy-zz** [haroldtreen/show-code#4]
Hey man,

I was in need of a package to display multiple snippets of code in a page. Like in a tutorial that you want to display the final result, and the code written below.

I see that this package is prepared for only one code to display. 

Are you interested in modifying this package to support multiple snippets of code in a single page?

**Comment by haroldtreen** [comment]
Hey @gabrielgodoy !

That's interesting. I'm hearing you have multiple code snippets on a page and want to display them with this package? I hadn't really thought of that use case. This is more about creating a silly visual effect :).

It's not something I was planning on adding. Do you have a link to the content where you're currently using it?

In any case, you're welcome to fork this package and adapt it however you like. Allowing for multiple `sc-containers` would probably be pretty easy to add.
